try {
  // Code that may throw error
let user;
console.log(user.name)
} catch (error) {
  console.error("Error caught:", error.message);
}
